### ISSUE TITLE
Remove the fake sponsors

### ISSUE THREAD

**Issue by OmgImAlexis** [minor/plutonium#1]
I’d suggest removing the fake sponsors since none of them actually sponsor this project.

**Comment by minor** [comment]
Do you think it would be alright if I keep a disclaimer underneath the logos? There was styling done on the logo that I wanted to highlight -- if not, I can put my own logo.

**Comment by minor** [comment]
Commit d7e6259ddfe7b13dff30764a213ba584ad0cf616 fixes the sponsors so I'll close the issue -- let me know if there is anything else.
